### ISSUE TITLE
Wrong msg maxlength is displayed on website load

### ISSUE THREAD

**Issue by m-rey** [nokonoko/Pomf-Board#3]
When you haven't interacted with the message textbox yet, the wrong message maxlength is shown. Afaik, the current msg maxlength is 1000.
This line is responsible for showing the max message length:
https://github.com/nokonoko/Pomf-Board/blob/27a9654b1e2f74a5f2511213d034b34482a3e08e/index.php#L20

**Comment by nokonoko** [comment]
Changed value to 1000, should be fine now, works for me at least.

**Comment by m-rey** [comment]
Fixed in 41af85a3e1190fb60c22cb13ff29ca72c2090506
